### ISSUE TITLE
💡 Feature request: Create a dark theme

### ISSUE THREAD

**Issue by mbos2** [mbos2/astro-dev-starter#17]
### What would you like to see?

Create a dark theme

- Create a dark theme colors (complementing #16)
- Create a theme switcher button and implement logic

Add the button somewhere in the navigation bar 

### Code of Conduct & Contribution Guidelines

- [X] I agree to follow this project's Code of Conduct and Contribution Guidelines

**Comment by Knochenmark** [comment]
https://web.dev/building-a-theme-switch-component/

**Comment by mbos2** [comment]
#25
