### ISSUE TITLE
💡 Feature request:  Create typography styles

### ISSUE THREAD

**Issue by mbos2** [mbos2/astro-dev-starter#22]
### What would you like to see?

Typography should involve:

- Same font family across the whole application
- font sizes for textual elements (Eg: paragraphs, headings, articles, and such)

Typography should be responsive to different screen sizes

### Code of Conduct & Contribution Guidelines

- [X] I agree to follow this project's Code of Conduct and Contribution Guidelines

**Comment by Shivashish-rwt** [comment]
I'll contribute to this. Can u please assign this to me?

**Comment by mbos2** [comment]
> I'll contribute to this. Can u please assign this to me?

Assigned. 
Expecting first PR draft within a few days.
